### ISSUE TITLE
What is that? A question about the layout.

### ISSUE THREAD

**Issue by ThDev-only** [Iyxan23/rafflesia#4]
I found the idea of this custom language interesting.

I was wondering, can I create a layout using this language and compile it, generating the correct XML files according to what I wrote with Rafflesia?

**Comment by iyxan23** [comment]
Hi @ThDev-only, rafflesia is only targeted to compile to Sketchware project files. It currently is not possible to generate layout XML files based off of rafflesia's layout syntax.

**Comment by ThDev-only** [comment]
I see, what a shame, but in this case the layout would become .flat files? Since Sketchware does this with aapt2 for layout files

I really wanted to use this to make creating layouts in my project easier...

**Comment by iyxan23** [comment]
> I see, what a shame, but in this case the layout would become .flat files? Since Sketchware does this with aapt2 for layout files
> 
> I really wanted to use this to make creating layouts in my project easier...

Terribly sorry, I forgot to reply.

Rafflesia compiles `.layout` files into the format Sketchware uses to store layouts with the help of [swrs](https://github.com/iyxan23/swrs) (another project I developed that could create, parse and edit Sketchware projects).

More or less the output looks something like the following (this is the raw AES-decrypted form of Sketchware's `view` file):

```
@main.xml
{"adSize":"","adUnitId":"","alpha":1.0,"checked":0,"choiceMode":0,"clickable":1,"customView":"","dividerHeight":1,"enabled":1,"firstDayOfWeek":1,"id":"vscroll1","image":{"rotate":0,"scaleType":"CENTER"},"indeterminate":"false","index":0,"layout":{"backgroundColor":16777215,"gravity":0,"height":-2,"layoutGravity":0,"marginBottom":8,"marginLeft":0,"marginRight":0,"marginTop":0,"orientation":-1,"paddingBottom":0,"paddingLeft":0,"paddingRight":0,"paddingTop":0,"weight":1,"weightSum":0,"width":-1},"max":100,"parent":"root","parentType":0,"preId":"vscroll1","preIndex":0,"preParentType":0,"progress":0,"progressStyle":"?android:progressBarStyle","scaleX":1.0,"scaleY":1.0,"spinnerMode":1,"text":{"hint":"","hintColor":-10453621,"imeOption":0,"inputType":1,"line":0,"singleLine":0,"text":"","textColor":-16777216,"textFont":"default_font","textSize":12,"textType":0},"translationX":0.0,"translationY":0.0,"type":12}
... more of these ...
{"adSize":"","adUnitId":"","alpha":1.0,"checked":0,"choiceMode":0,"clickable":1,"customView":"","dividerHeight":1,"enabled":1,"firstDayOfWeek":1,"id":"raminfo","image":{"rotate":0,"scaleType":"CENTER"},"indeterminate":"false","index":1,"layout":{"backgroundColor":16777215,"gravity":0,"height":-2,"layoutGravity":0,"marginBottom":0,"marginLeft":0,"marginRight":0,"marginTop":0,"orientation":-1,"paddingBottom":8,"paddingLeft":8,"paddingRight":8,"paddingTop":8,"weight":0,"weightSum":0,"width":-2},"max":100,"parent":"linear2","parentType":0,"preId":"","preIndex":0,"preParentType":0,"progress":0,"progressStyle":"?android:progressBarStyle","scaleX":1.0,"scaleY":1.0,"spinnerMode":1,"text":{"hint":"","hintColor":-10453621,"imeOption":0,"inputType":1,"line":0,"singleLine":0,"text":"TextView","textColor":-16777216,"textFont":"default_font","textSize":12,"textType":0},"translationX":0.0,"translationY":0.0,"type":4}

@main.xml_fab
{"adSize":"","adUnitId":"","alpha":1.0,"checked":0,"choiceMode":0,"clickable":1,"customView":"","dividerHeight":1,"enabled":1,"firstDayOfWeek":1,"id":"_fab","image":{"rotate":0,"scaleType":"CENTER"},"indeterminate":"false","index":0,"layout":{"backgroundColor":16777215,"gravity":0,"height":-2,"layoutGravity":85,"marginBottom":16,"marginLeft":16,"marginRight":16,"marginTop":16,"orientation":-1,"paddingBottom":0,"paddingLeft":0,"paddingRight":0,"paddingTop":0,"weight":0,"weightSum":0,"width":-2},"max":100,"parentType":-1,"preIndex":0,"preParentType":0,"progress":0,"progressStyle":"?android:progressBarStyle","scaleX":1.0,"scaleY":1.0,"spinnerMode":1,"text":{"hint":"","hintColor":-10453621,"imeOption":0,"inputType":1,"line":0,"singleLine":0,"text":"","textColor":-16777216,"textFont":"default_font","textSize":12,"textType":0},"translationX":0.0,"translationY":0.0,"type":16}
```

I wouldn't recommend following the same approach that Sketchware uses. Their method is clunky, and since Sketchware is no longer actively maintained, there's no benefit in being compatible with it.

It's possible to re-use the same code that rafflesia uses to parse the layout syntax, located [here](https://github.com/iyxan23/rafflesia/blob/e0f8a2349c42388891165d62f15e0b4e0a7e3ea1/rafflesia/src/rafflesia/compiler/layout/parser.rs). But this involves a lot of code to copy, and might be pretty difficult if your project is not based off of rust.

I suppose the best course of action is to rewrite the same parser and work from there, if the effort is feasible.

Let me know if you have any more questions regarding rafflesia!
